---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: app1
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDLj36jjo3pln5JHi3NA7zYOpWOhPndTsnh35YWSBeunG0HzZLx66JPR+nJ+oGIH99KBqPNuc0M7LeQNYNLdInp2vCwgT484T+k1ApLZJSB86KYRXmsXFTAbWr0jajEBcnM1ppSILGHfbJ5rQDbUJueg+kQsRzBLQ8ZcqvjV/7yiPx67KzvyWQlPFkx2mp77PRQ2nrXOz076OYzb55hbn4TSqk6uewmy/N4cqKF5kO8L8Nf2n0EvnyJED1A4dc8VAEcPdSiA7eCBEQRLG1lnznDQKYrkNzICGUcc501XZzrNFecKG6xsS715g3p2TY/phyrQ2M7atQKO5wSuLO89I5YiZoJJ/NyTUX9KLL15FXBLvPqxCILbmCJhi+mPunj9m8X9IVcamz/n8d5sQmGbouEIwTIdAYbfpv1qVIKFJtXXul1CDWzxhhuVOHXEq6gT47UWRm1nBxtOf8GChsIXxSSKsy1GVSS9l/c6TYKgijhz8RdGCaOcqPw1b0dM13fBLIlVfjhTG1AOL7QfPM5EfTBMg6MVmZ2xArRsA2MhxQv9E+WHNeDr++uMhyVxCU4+dAWg5SbhtW8lZXmWMryN7oQREun1DrgvAZhgjHXn4EeeAR/8/xDMOlhpAzUWqvfTS7doGses/5VaHJL3B8ppsQsxwGTE8HyX+73eMOJASWNMZlSVXaFg15jJvD1t3/gdRaxxRijLKQxvr12cjIg7mLg9Gl/rw==
    AWS_SECRET_ACCESS_KEY: AgB8bQhaosmFDynSCf7wMfszEaAcFqjtZN+DvKocXEG69DaJmU1qAtViPJF2ck71pIzV9GKS9x6dHH3bHjeeDRVtckRu8z6D1UpsKPyYDikfjP73B8gr3o+qaNjT1TeDS5deiyU4BwV+4vdXs9Xj8x8yAdmMu/FhnlyQLh3UuG4o3zjNfCVIe5TSEGTg6XQ8PR+hwWs5N/jwCkch4WEGuOtecBS6H7XgmUV4H0eovEO7RyJTJA92jHxNBaJneZWicU7Wk7JjiUk7XtTPlShdJGHKiz5hyyhLbMiFroPrfIkIdxl2+csIzV6NslprSA1cpU+wf08InhwsDZb/WqIqSYF9CQXQkMiZDdXF9CyyCV5xDSde3174D5kVf0DzVk63QYcY8y4Vje9M2j1IzD/Dt4g90WkPAlZN0jWXeFMN7000H1oE6xnWsmasA8lsCeHr28AWWJ9W8Xo2vX/Xj5HkeUvpkP7AsYvqhcKcgL0djkBWYzpDKKnjUB1m/CJOYmzPaJLSU90Oi60mbPUk0nk+bRFV4PlQoxF4m3ApSA60Oiw9h32A2gdkH4o8Fz3i2Rc+IlrrTjlgaZ3W+o6AZ8wnsquXNUuhvggMGWG7O3qqCwGVkJwuf/dfFTT71W9hgEMU7tP/LS5AkUpKVfImWOS+CazMNkp5TAnTDWN+9sTurfoK24MfUs0rDN9OcC/DVinmwpAzSFhosu7lF8vEbReBUjAG07xfv1vFbVKd/PkuiMeEjbm/o9GIfHq9
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: app1
